# Generated by Django 4.1.3 on 2022-12-01 19:29

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('DoB', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
            ],
        ),
    ]
